[project]
name = "nodc-station"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "a001985", email = "magnus.wenzer@smhi.se" }
]
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.0",
    "polars>=1.31.0",
    "pyarrow>=20.0.0",
    "pyproj>=3.7.1",
]

[project.scripts]
nodc-station = "nodc_station:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = [
    "A",  # flake8-builtins
    "F",  # pyflakes
    "E", # pycodestyle: error
    "W",  # pycodestyle: warning
    "I",  # isort: unsorted-imports
    "RUF"  # Ruff-specific rules
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.1",
]
